package com.example.eclipselinkuuidtest;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.HashMap;
import java.util.Map;

import javax.sql.DataSource;

import org.eclipse.persistence.config.PersistenceUnitProperties;
import org.postgresql.util.PSQLException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.context.annotation.Bean;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.orm.jpa.JpaTransactionManager;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.orm.jpa.vendor.EclipseLinkJpaVendorAdapter;
import org.springframework.test.context.TestPropertySource;
import org.springframework.transaction.PlatformTransactionManager;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import jakarta.persistence.EntityManagerFactory;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

@Testcontainers
@SpringBootTest(classes = EclipseLinkUuidNullPostgresTest.TestApplication.class)
@TestPropertySource(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.sql.init.mode=never"
})
class EclipseLinkUuidNullPostgresTest {

    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @Autowired
    JdbcTemplate jdbcTemplate;

    @Autowired
    GizmoRepository repository;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("drop table if exists gizmo");
        jdbcTemplate.execute("""
                create table gizmo (
                    id integer generated by default as identity primary key,
                    gizmo_id uuid
                )
                """);
    }

    @Test
    void savingEntityWithUnsetUuidFieldReproducesEclipseLinkUuidNullBindingBug() {
        Gizmo gizmo = new Gizmo();

        assertThatThrownBy(() -> repository.saveAndFlush(gizmo))
                .satisfies(throwable -> {
                    assertThat(causalChainContains(throwable, PSQLException.class))
                            .as("causal chain contains PostgreSQL's PSQLException")
                            .isTrue();
                    assertThat(causalChainMessage(throwable))
                            .contains("gizmo_id")
                            .contains("uuid")
                            .contains("character varying");
                });
    }

    private static boolean causalChainContains(Throwable throwable, Class<? extends Throwable> type) {
        Throwable current = throwable;
        while (current != null) {
            if (type.isInstance(current)) {
                return true;
            }
            current = current.getCause();
        }
        return false;
    }

    private static String causalChainMessage(Throwable throwable) {
        StringBuilder builder = new StringBuilder();
        Throwable current = throwable;
        while (current != null) {
            if (current.getMessage() != null) {
                builder.append(current.getMessage()).append('\n');
            }
            current = current.getCause();
        }
        return builder.toString();
    }

    @SpringBootConfiguration
    @EnableAutoConfiguration(exclude = HibernateJpaAutoConfiguration.class)
    @EnableJpaRepositories(basePackageClasses = GizmoRepository.class)
    static class TestApplication {

        @Bean
        LocalContainerEntityManagerFactoryBean entityManagerFactory(DataSource dataSource) {
            EclipseLinkJpaVendorAdapter vendorAdapter = new EclipseLinkJpaVendorAdapter();
            vendorAdapter.setGenerateDdl(false);
            vendorAdapter.setShowSql(true);
            vendorAdapter.setDatabasePlatform("org.eclipse.persistence.platform.database.PostgreSQLPlatform");

            Map<String, Object> properties = new HashMap<>();
            properties.put(PersistenceUnitProperties.WEAVING, "false");
            properties.put(PersistenceUnitProperties.DDL_GENERATION, PersistenceUnitProperties.NONE);
            properties.put(PersistenceUnitProperties.TARGET_DATABASE, "org.eclipse.persistence.platform.database.PostgreSQLPlatform");
            properties.put(PersistenceUnitProperties.LOGGING_LEVEL, "FINE");
            properties.put(PersistenceUnitProperties.LOGGING_PARAMETERS, "true");

            LocalContainerEntityManagerFactoryBean factoryBean = new LocalContainerEntityManagerFactoryBean();
            factoryBean.setPersistenceProviderClass(org.eclipse.persistence.jpa.PersistenceProvider.class);
            factoryBean.setDataSource(dataSource);
            factoryBean.setJpaVendorAdapter(vendorAdapter);
            factoryBean.setPackagesToScan(Gizmo.class.getPackageName());
            factoryBean.setJpaPropertyMap(properties);
            return factoryBean;
        }

        @Bean
        PlatformTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
            return new JpaTransactionManager(entityManagerFactory);
        }
    }
}
